### ISSUE TITLE
Z-Axis NEMA 23 Mount.stl on Zip on Main Page don't have the Mounthing Hole

### ISSUE THREAD

**Issue by excessnet** [threedesigns/printNC#3]
The "Z-Axis NEMA 23 Mount.stl" on the ZIP is using the wrong version.

I suggest removing any download files from the webpage and redirect people here where fille will be up to date.

**Comment by BiuTse** [comment]
For which beam Dimension?

**Comment by excessnet** [comment]
Was for the 2x3

**Comment by BiuTse** [comment]
ok thx.
Asked Hoges if he could provide the right files.

**Comment by BiuTse** [comment]
Here in this project the files are now correct. But on the Homepage they are still wrong.
Will close the issue, when it's also done on the main page

**Comment by BiuTse** [comment]
Hoges fixed files

**Comment by excessnet** [comment]
don't fix it, remove completely and point to the file here !
