### ISSUE TITLE
Remove Wiki

### ISSUE THREAD

**Issue by NeoKurtex** [threedesigns/printNC#56]
In efforts to streamline documentation, I would like to remove the github wiki pages and link to the wikijs site we are building. Any concerns?

[https://wiki.printnc.info/en/home](https://wiki.printnc.info/en/home)

**Comment by LoganFraser** [comment]
That seems reasonable to me. I think the wiki here is hard to find for many people. Having it linked from the main github page would help that, but if the new one is easier to design and contribute to, I'm all for it.

**Comment by NeoKurtex** [comment]
The new wiki should be much easier to work with. It allows for Discord and site-specific logins, has a WYSIWYG editor, and has local image hosting. 

The only barrier to get started is obtaining 'contributor' status. Anyone who has made an account thus far is already a contributor. 

If you would like to contribute but have not yet made an account, that's the first step.
From there, we can edit your privileges. 

This wiki should be gone by this weekend unless anyone has any hesitations.

**Comment by jaymis** [comment]
Maybe wait until the external wiki has at least some level of content organisation? It seems pretty bare at the moment, unless there's something I'm missing? The current wiki home page has at least a good starting point: https://github.com/threedesigns/printNC/wiki

Whereas the new one has "test test" https://wiki.printnc.info/en/home

**Comment by LoganFraser** [comment]
Also: 

Drivers
Drivers!
asdasdasdasd

**Comment by NeoKurtex** [comment]
Everything is already in the wiki, the pages just need to be added to the navigation bar.. should take me a few minutes

**Comment by NeoKurtex** [comment]
File contents are now fully migrated
